### ISSUE TITLE
question related to https://keestalkstech.com/2013/01/comparing-files-with-powershell/

### ISSUE THREAD

**Issue by caspertone2003** [KeesCBakker/synology-ci-cd-nodejs-demo#2]
Hi,
sorry for using this way to contact you around above topic, I am unable to find an email of yours outside linkedin...

I have been long searching for a tool to determine in the less possible time if two binaries (or whatever content files) are equal or not.
To my surprise, I have been unable to find a good tool in windows. Your blog post provides a good algorithmic approach but I have not found a way to automate it. I am not powershell knowledgeable... (just cmd bat oriented)
After some searching and learning, I was able to use the function using PowerShell ISE. 

by the way, had to change lines
    if ($first.Length -ne $second.Length) return $false
    if ( $bufferSize -eq 0 ) $bufferSize = 524288

to
    if ( $first.Length -ne $second.Length ) {return $false} 
    if ( $bufferSize -eq 0 )  {$bufferSize = 524288} 

Could you help me to automate this a bit?

Ideally, I would need a bat or equivalente that would execute as
"compare file1 file2 >result.txt"

Could you help me in wrapping the powershell to be able to run it in that way?

TIA
CT

**Comment by KeesCBakker** [comment]
Hi, just saw your comment by accident. Super that you are reaching out. Let me see what I can do for you.

**Comment by KeesCBakker** [comment]
This might help you: https://keestalkstech.com/2013/01/comparing-files-with-powershell/#just-need-a-script

**Comment by caspertone2003** [comment]
Thanks!
It helped a lot!

Compare.ps1 works smoothly!

==================================================================

For TLDR ones, my quick and dirty Comparefiles.bat on top of Compare.ps1:

Comparefiles.bat:
REM start of bat --------------------------------------
set _f1=file1.avi
set _f2=file 3.avi
ECHO %_f1% FILE IS BINARY EQUAL TO %_f2% FILE?
PowerShell -NoProfile -ExecutionPolicy Bypass -Command "& './Compare.ps1' '%_f1%' '%_f2%'"
pause
REM end of bat --------------------------------------

[note that this assumes Comparefiles.bat and Compare.ps1 are in the same directory; filesnames might have spaces - surely all can be done more compact and efficient, but it is the way I found...]
hope this helps!!

(one last point on Compare.ps1... one can produce a compare.exe -with and withoug GUI using https://gallery.technet.microsoft.com/scriptcenter/PS2EXE-GUI-Convert-e7cb69d5 )

==============================================================

To learn a bit:

a) how to achieve that Compare.ps1 is executed?
https://www.itprotoday.com/powershell/how-run-powershell-script
https://www.windowscentral.com/how-create-and-run-your-first-powershell-script-file-windows-10

b) how to do it from a bat file?
https://blog.danskingdom.com/allow-others-to-run-your-powershell-scripts-from-a-batch-file-they-will-love-you-for-it/
https://stackoverflow.com/questions/19335004/how-to-run-a-powershell-script-from-a-batch-file

PS: I tough I new more about PS than what I actually knew... not that I know much more now but I am able to compare two files as binaries in an efficient way with Kees excellent tool

**Comment by KeesCBakker** [comment]
Cool. Let me close this issue as it is not really related to this the nodejs-demo. Happy scripting!
